-- MySQL Script generated by MySQL Workbench
-- Sat Dec  2 20:43:43 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema 666danila
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema 666danila
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `666danila` DEFAULT CHARACTER SET utf8 ;
USE `666danila` ;

-- -----------------------------------------------------
-- Table `666danila`.`zakazu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `666danila`.`zakazu` (
  `idzakazu` INT NOT NULL AUTO_INCREMENT,
  `usluga` VARCHAR(45) NOT NULL,
  `cost_of_usluga` INT NOT NULL,
  `company_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idzakazu`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
